### ISSUE TITLE
All declarations of 'observable' must have identical modifiers

### ISSUE THREAD

**Issue by svstartuplab** [zenparsing/zen-observable#52]
ERROR in node_modules/@types/zen-observable/index.d.ts(9,18): error TS2687: All declarations of 'observable' must have identical modifiers.

Other dependencies have had this problem around June 1.  Apparently it is related to an RXJS update.

I need to roll back from the latest version.  This is a dependency of one of my Angular dependencies.

**Comment by eugene1g** [comment]
This has been fixed by DefinitelyTyped [https://github.com/DefinitelyTyped/DefinitelyTyped/issues/26198] but your Angular dependency probably pins typings to the old version. You can try adding the latest dependency directly to your package.json e.g. `yarn add -D @types/zen-observable` which will bring in the updated typings and make `tsc` happy.

**Comment by zenparsing** [comment]
Assuming that this has been resolved in DefinitelyTyped. Please reopen if necessary.

**Comment by awtrimpe** [comment]
For a hotfix to get the error to go away, remove readonly so it looks like:

```javascript
interface SymbolConstructor {
    observable: symbol;
  }
```
